<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
    <Platforms>x64;ARM64</Platforms>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <Version>1.0.152</Version>
    <AssemblyTitle>Lhamiel</AssemblyTitle>
    <AssemblyDescription>圧縮・展開ソフトウェア</AssemblyDescription>
    <AssemblyCompany>1llum1n4t1s</AssemblyCompany>
    <AssemblyProduct>Lhamiel</AssemblyProduct>
    <AssemblyCopyright>Copyright © 2025-2026 ゆろち</AssemblyCopyright>
    <Title>Lhamiel</Title>
    <Authors>ゆろち</Authors>
  </PropertyGroup>
</Project>
