using System.Buffers;
namespace Lhamiel.Util;

/// <summary>
/// 起動時に前回実行で残存した一時ディレクトリを掃除するユーティリティ。
/// OneDrive 同期フォルダや強制終了・ディスクフル等で Lhamiel_* 一時フォルダが
/// 残る不具合（/rere P1 #10）の軽減策。
/// </summary>
internal static class TempCleanup
{
    /// <summary>
    /// 掃除対象とする「Lhamiel が自動生成する一時ディレクトリ」の既知プレフィックス。
    /// ユーザーが手動で作った `Lhamiel_Project` のようなフォルダを誤削除しないよう
    /// 具体名で絞り、末尾に GUID("N" 形式・32桁 16進) が続くもののみを対象にする。
    /// </summary>
    private static readonly string[] KnownAutoGeneratedPrefixes =
    [
        "Lhamiel_Temp_",     // ExtractViaTempFolderAsync が作る中間ディレクトリ
        "Lhamiel_Extract_",  // ExtractArchive 内部の一時展開先
    ];

    /// <summary>
    /// %TEMP% 配下でのみ掃除する「ハイフン区切り」パターン。
    /// PartialExtractionHandler / ArchiveErrorHandler が使う `lhamiel-&lt;GUID-D形式&gt;` に対応。
    /// 出力先ディレクトリ配下には作らないため、%TEMP% 限定の扱いで安全性を保つ。
    /// </summary>
    private const string TempOnlyDashPrefix = "lhamiel-";

    /// <summary>掃除対象とみなすまでの最小経過時間。現在実行中の他プロセスを誤って消さないためのガード</summary>
    private static readonly TimeSpan MinAge = TimeSpan.FromMinutes(30);

    /// <summary>
    /// %TEMP% 配下および設定された出力先の直下にある、Lhamiel 自動生成と識別できる
    /// 古いフォルダのみを削除する。ユーザー作成フォルダを巻き込まないように
    /// プレフィックス + GUID 形式の両方で一致したもののみを対象にする。
    /// </summary>
    /// <remarks>
    /// ベストエフォート。エラーはログだけ残して続行する。
    /// 最終更新日時が <see cref="MinAge"/> より古いものだけを対象にすることで、
    /// 現在実行中のプロセスの tempDir を誤削除しないようにする。
    /// </remarks>
    public static void CleanupOrphanedTempDirectories()
    {
        try
        {
            var tempRoot = Path.GetTempPath();

            // 設定された出力先は「Lhamiel_Temp_<GUID>」のみ掃除対象（ExtractViaTempFolderAsync が
            // 出力先直下に作るため）。ユーザーが意図的に置いたファイルを守るため対象パターンを
            // 狭くする。
            var outputRoots = new List<string>();
            try
            {
                var settings = SettingsManager.Instance.Current;
                if (!string.IsNullOrWhiteSpace(settings.ExtractionOutputDirectory))
                    outputRoots.Add(settings.ExtractionOutputDirectory);
                if (!string.IsNullOrWhiteSpace(settings.CompressionOutputDirectory))
                    outputRoots.Add(settings.CompressionOutputDirectory);
            }
            catch
            {
                // SettingsManager 未初期化でも続行
            }

            var now = DateTime.UtcNow;
            var deleted = 0;

            // %TEMP%: 既知プレフィックス全種 + lhamiel- プレフィックスを対象
            deleted += CleanRoot(tempRoot, now, includeDashPrefix: true);

            // 出力先: 「Lhamiel_Temp_<GUID>」のみに限定（出力先直下に作られる唯一のパターン）
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var root in outputRoots)
            {
                if (string.IsNullOrWhiteSpace(root)) continue;
                string normalized;
                try { normalized = Path.GetFullPath(root); }
                catch { continue; }
                if (string.Equals(normalized, Path.GetFullPath(tempRoot), StringComparison.OrdinalIgnoreCase)) continue;
                if (!seen.Add(normalized)) continue;

                deleted += CleanRoot(normalized, now, includeDashPrefix: false, onlyPrefixes: ["Lhamiel_Temp_"]);
            }

            if (deleted > 0)
                Logger.Log($"残存一時ディレクトリを {deleted} 件削除しました");
        }
        catch (Exception ex)
        {
            Logger.Log($"TempCleanup でエラー: {ex.Message}", LogLevel.Warning);
        }
    }

    /// <summary>指定ルート配下の Lhamiel 自動生成フォルダを掃除する。</summary>
    /// <param name="root">掃除対象のルートディレクトリ</param>
    /// <param name="now">現在時刻（UTC）</param>
    /// <param name="includeDashPrefix">`lhamiel-` プレフィックスも対象にするか（%TEMP% 限定）</param>
    /// <param name="onlyPrefixes">掃除対象プレフィックス（null の場合は KnownAutoGeneratedPrefixes 全部）</param>
    /// <returns>削除件数</returns>
    private static int CleanRoot(string root, DateTime now, bool includeDashPrefix, string[]? onlyPrefixes = null)
    {
        if (!Directory.Exists(root)) return 0;

        var prefixes = onlyPrefixes ?? KnownAutoGeneratedPrefixes;
        var deleted = 0;

        IEnumerable<string> dirs;
        try
        {
            dirs = Directory.EnumerateDirectories(root, "*", SearchOption.TopDirectoryOnly);
        }
        catch (Exception ex)
        {
            Logger.Log($"一時フォルダ列挙に失敗: {root}, {ex.Message}", LogLevel.Warning);
            return 0;
        }

        foreach (var dir in dirs)
        {
            var name = Path.GetFileName(dir);
            if (!IsLhamielAutoGenerated(name, prefixes, includeDashPrefix)) continue;

            try
            {
                var lastWrite = Directory.GetLastWriteTimeUtc(dir);
                if (now - lastWrite < MinAge) continue;

                Directory.Delete(dir, recursive: true);
                deleted++;
                Logger.Log($"残存一時ディレクトリを削除: {dir}", LogLevel.Debug);
            }
            catch (Exception ex)
            {
                Logger.Log($"残存一時ディレクトリ削除失敗（無視）: {dir}, {ex.Message}", LogLevel.Debug);
            }
        }

        return deleted;
    }

    /// <summary>
    /// フォルダ名が Lhamiel の自動生成一時ディレクトリに一致するか判定する。
    /// プレフィックスの一致だけでなく、末尾が GUID 形式であることも要求する。
    /// </summary>
    private static bool IsLhamielAutoGenerated(string name, string[] prefixes, bool includeDashPrefix)
    {
        foreach (var prefix in prefixes)
        {
            if (name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            {
                var suffix = name[prefix.Length..];
                if (IsGuidNFormat(suffix)) return true;
            }
        }

        if (includeDashPrefix && name.StartsWith(TempOnlyDashPrefix, StringComparison.OrdinalIgnoreCase))
        {
            var suffix = name[TempOnlyDashPrefix.Length..];
            if (IsGuidDFormat(suffix)) return true;
        }

        return false;
    }

    /// <summary>
    /// GUID "N" 形式（ハイフンなし 32 桁 16 進）か判定。
    /// <see cref="Guid.NewGuid()"/>.ToString("N") が生成する形式に対応。
    /// </summary>
    private static bool IsGuidNFormat(string s) =>
        s.Length == 32 && s.AsSpan().IndexOfAnyExcept(HexDigits) < 0;

    /// <summary>
    /// GUID "D" 形式（ハイフン区切り 36 桁）か判定。
    /// <see cref="Guid.NewGuid()"/>.ToString() の既定形式。
    /// </summary>
    private static bool IsGuidDFormat(string s) => Guid.TryParseExact(s, "D", out _);

    private static readonly SearchValues<char> HexDigits = SearchValues.Create("0123456789abcdefABCDEF");
}
