using System.Buffers;
namespace Lhamiel.Util;

/// <summary>
/// 起動時に前回実行で残存した一時ディレクトリを掃除するユーティリティ。
/// OneDrive 同期フォルダや強制終了・ディスクフル等で Lhamiel_* 一時フォルダが
/// 残る不具合（/rere P1 #10）の軽減策。
/// </summary>
/// <remarks>
/// <b>安全性ポリシー</b>:
/// <list type="bullet">
///   <item><description>掃除対象は <see cref="Path.GetTempPath"/>（%TEMP%）配下のみ。
///   ユーザー設定の出力先（Desktop / Documents 等）は絶対に走査しない。</description></item>
///   <item><description>ディレクトリ名は既知プレフィックス（<c>Lhamiel_Temp_</c> / <c>Lhamiel_Extract_</c> /
///   <c>lhamiel-</c>）で絞り、末尾が GUID 形式（N=32桁hex または D=ハイフン区切り36桁）であることも検証する。</description></item>
///   <item><description>最終更新日時が <see cref="MinAge"/>（30分）を超えるものだけを対象にし、
///   現在実行中の他プロセスの一時ディレクトリを誤削除しない。</description></item>
/// </list>
/// </remarks>
internal static class TempCleanup
{
    /// <summary>
    /// 掃除対象とする「Lhamiel が自動生成する一時ディレクトリ」のアンダースコア区切りプレフィックス。
    /// 末尾は Guid("N") 形式（32桁16進）が続く前提。
    /// </summary>
    private static readonly string[] UnderscoreNamedAutoGeneratedPrefixes =
    [
        "Lhamiel_Temp_",     // ExtractViaTempFolderAsync が作る中間ディレクトリ
        "Lhamiel_Extract_",  // ExtractArchive 内部の一時展開先
    ];

    /// <summary>
    /// ハイフン区切りプレフィックス。PartialExtractionHandler / ArchiveErrorHandler が
    /// 使う <c>lhamiel-&lt;Guid-D&gt;</c> パターンに対応。
    /// </summary>
    private const string DashNamedAutoGeneratedPrefix = "lhamiel-";

    /// <summary>掃除対象とみなすまでの最小経過時間。現在実行中の他プロセスを誤って消さないためのガード</summary>
    private static readonly TimeSpan MinAge = TimeSpan.FromMinutes(30);

    /// <summary>
    /// %TEMP% 配下の、Lhamiel が自動生成したと識別できる古いフォルダのみを削除する。
    /// ユーザー設定の出力先は <b>一切走査しない</b> ため、ユーザーデータを誤削除しない。
    /// </summary>
    /// <remarks>
    /// ベストエフォート。エラーはログだけ残して続行する。
    /// </remarks>
    public static void CleanupOrphanedTempDirectories()
    {
        try
        {
            var tempRoot = Path.GetTempPath();
            var deleted = CleanRoot(tempRoot, DateTime.UtcNow);

            if (deleted > 0)
                Logger.Log($"残存一時ディレクトリを {deleted} 件削除しました（%TEMP% 配下）");
        }
        catch (Exception ex)
        {
            Logger.Log($"TempCleanup でエラー: {ex.Message}", LogLevel.Warning);
        }
    }

    /// <summary>指定ルート配下の Lhamiel 自動生成フォルダを掃除する。</summary>
    /// <param name="root">掃除対象のルートディレクトリ（%TEMP% のみが想定）</param>
    /// <param name="now">現在時刻（UTC）</param>
    /// <returns>削除件数</returns>
    private static int CleanRoot(string root, DateTime now)
    {
        if (!Directory.Exists(root)) return 0;

        var deleted = 0;
        IEnumerable<string> dirs;
        try
        {
            dirs = Directory.EnumerateDirectories(root, "*", SearchOption.TopDirectoryOnly);
        }
        catch (Exception ex)
        {
            Logger.Log($"一時フォルダ列挙に失敗: {root}, {ex.Message}", LogLevel.Warning);
            return 0;
        }

        foreach (var dir in dirs)
        {
            var name = Path.GetFileName(dir);
            if (!IsLhamielAutoGenerated(name)) continue;

            try
            {
                var lastWrite = Directory.GetLastWriteTimeUtc(dir);
                if (now - lastWrite < MinAge) continue;

                Directory.Delete(dir, recursive: true);
                deleted++;
                Logger.Log($"残存一時ディレクトリを削除: {dir}", LogLevel.Debug);
            }
            catch (Exception ex)
            {
                Logger.Log($"残存一時ディレクトリ削除失敗（無視）: {dir}, {ex.Message}", LogLevel.Debug);
            }
        }

        return deleted;
    }

    /// <summary>
    /// フォルダ名が Lhamiel の自動生成一時ディレクトリに一致するか判定する。
    /// プレフィックスの一致だけでなく、末尾が GUID 形式（N または D）であることも要求する。
    /// </summary>
    private static bool IsLhamielAutoGenerated(string name)
    {
        foreach (var prefix in UnderscoreNamedAutoGeneratedPrefixes)
        {
            if (name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            {
                var suffix = name[prefix.Length..];
                if (IsGuidNFormat(suffix)) return true;
            }
        }

        if (name.StartsWith(DashNamedAutoGeneratedPrefix, StringComparison.OrdinalIgnoreCase))
        {
            var suffix = name[DashNamedAutoGeneratedPrefix.Length..];
            if (IsGuidDFormat(suffix)) return true;
        }

        return false;
    }

    /// <summary>
    /// GUID "N" 形式（ハイフンなし 32 桁 16 進）か判定。
    /// <see cref="Guid.NewGuid()"/>.ToString("N") が生成する形式に対応。
    /// </summary>
    private static bool IsGuidNFormat(string s) =>
        s.Length == 32 && s.AsSpan().IndexOfAnyExcept(HexDigits) < 0;

    /// <summary>
    /// GUID "D" 形式（ハイフン区切り 36 桁）か判定。
    /// <see cref="Guid.NewGuid()"/>.ToString() の既定形式。
    /// </summary>
    private static bool IsGuidDFormat(string s) => Guid.TryParseExact(s, "D", out _);

    private static readonly SearchValues<char> HexDigits = SearchValues.Create("0123456789abcdefABCDEF");
}
